.TH ASPLIT 1
.SH NAME
.B asplit
- splits lines by string
.SH SYNOPSIS
.B asplit
.I STRING
[
.I SELECTION
]
.SH DESCRIPTION
Prints the span of text between and excluding occurrences SELECTION-1 and SELECTION of STRING in each line from standard input.
.PP
With no SELECTION, prints the amount of times STRING occurs in each line.
.SH BUGS
If SELECTION isn't a natural number it'll be interpreted as 0.
.PP
asplit is a wrapper for awk and is redundant.
.SH DIAGNOSTICS
asplit will return 0 only if the program completed a job successfully, and 1 if there were errors or no arguments were given.
.PP
When a line is received that exceeds the maximum characters asplit can handle, asplit will print a warning message to standard error.
.SH HISTORY
asplit was originally written in C and was not aware of character sets beyond ASCII (though its compatibility was probably fine), hence it was named asplit, for "ASCII split".
It was later rewritten in POSIX shell and awk.
.SH SEE ALSO
.IR awk (1)
