#!/usr/bin/python3

import argparse

parser = argparse.ArgumentParser(description='''\
Splits each line in textfile INPUT by the given STRING and outputs the SELECTION.
''')

parser.add_argument("input", type=argparse.FileType('r'))
parser.add_argument("string", type=str)
parser.add_argument("selection", type=int)

args = parser.parse_args()

# replaces stuff because bash trims out whitespace
special = {
	"\\t": "\t"
}

if args.string in special.keys(): args.string = special[args.string]

with args.input as file_object:
	while True:
		line = file_object.readline()
		if line == "": break
		line = line.rstrip().split(args.string)
		if len(line)-1 < args.selection: print("")
		else: print(line[args.selection])
